function [BW] = imsi(I)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 10-Jul-2022
%----------------------------------------------------

labI=rgb2lab(I)
ab = labI(:,:,2:3);
ab = im2single(ab);
pixel_labels = imsegkmeans(ab,3,'NumAttempts',1);
imshow(pixel_labels,[])
X = imgradient(pixel_labels);

% Create empty mask.
BW = false(size(X,1),size(X,2));

% 阈值化图像 - 全局阈值
BW = imbinarize(X);

% 使用 disk 执行掩膜闭运算
radius = 6;
decomposition = 8;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% 使用 disk 执行掩膜开运算
radius = 30;
decomposition = 8;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% 使用 disk 膨胀掩膜
radius = 3;
decomposition = 8;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

end

