function [BW] = morph2(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 11-Jul-2022
%----------------------------------------------------


% Create empty mask.
BW = false(size(X,1),size(X,2));

% 阈值化图像 - 全局阈值
BW = imbinarize(X);

% 反转掩膜
BW = imcomplement(BW);

% 使用 disk 腐蚀掩膜
radius = 1;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% 使用 disk 膨胀掩膜
radius = 8;
decomposition = 8;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% 使用 disk 执行掩膜开运算
radius = 30;
decomposition = 8;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% 填充孔
BW = imfill(BW, 'holes');

end

