function [BW,maskedImage] = morphcloseopen(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 14-Jul-2022
%----------------------------------------------------


% Create empty mask.
BW = false(size(X,1),size(X,2));

% 阈值化图像 - 全局阈值
BW = imbinarize(X);

% 使用 disk 执行掩膜闭运算
radius = 5;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% 使用 disk 执行掩膜开运算
radius = 31;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

